server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usermanagement
    username: postgres
    password: changeme
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
